### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by rgwozdz** [geotrellis/geotrellis-gdal#2]
`[error] (geotrellis-gdal/*:update) sbt.ResolveException: unresolved dependency: com.azavea.geotrellis#geotrellis-raster_2.10;0.10.0-SNAPSHOT: not found
[error] unresolved dependency: com.azavea.geotrellis#geotrellis-spark_2.10;0.10.0-SNAPSHOT: not found
[error] unresolved dependency: com.azavea.geotrellis#geotrellis-spark-etl_2.10;0.10.0-SNAPSHOT: not found`

**Comment by echeipesh** [comment]
Everything is bumped to use GeoTrellis 1.0.0 and gdal-2.1.0, no more SNAPSHOT versions.

Resolved by: https://github.com/geotrellis/geotrellis-gdal/pull/1
